'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FastCutter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;Config&gt;
        '''  &lt;GlobalConfig&gt;
        '''    &lt;RectWidth&gt;138,05&lt;/RectWidth&gt;
        '''    &lt;RectHeight&gt;201,65&lt;/RectHeight&gt;
        '''    &lt;XOfset&gt;0&lt;/XOfset&gt;
        '''    &lt;YOfset&gt;0&lt;/YOfset&gt;
        '''    &lt;OriginXY&gt;0&lt;/OriginXY&gt;
        '''    &lt;OriginZ&gt;0&lt;/OriginZ&gt;
        '''    &lt;InExtCutting&gt;0&lt;/InExtCutting&gt;
        '''    &lt;CwCCw&gt;0&lt;/CwCCw&gt;
        '''    &lt;CncFolderPath&gt;D:\&lt;/CncFolderPath&gt;
        '''    &lt;StartPoint&gt;0&lt;/StartPoint&gt;
        '''    &lt;DiaCutter&gt;2,1&lt;/DiaCutter&gt;
        '''    &lt;DepthPerPass&gt;2,1&lt;/DepthPerPass&gt;
        '''    &lt;StepCut&gt;0,9&lt;/StepCut&gt;
        '''    &lt;FeedSpeed&gt;1000&lt;/FeedSpeed&gt;
        '''    &lt;InFe [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _Default() As String
            Get
                Return ResourceManager.GetString("_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CutExtCCw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutExtCCw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CutExtCw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutExtCw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CutIntCCw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutIntCCw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CutIntCw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutIntCw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DragFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DragFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainRect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainRect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PocketHelixCCW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PocketHelixCCW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PocketHelixCW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PocketHelixCW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PocketX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PocketX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PocketY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PocketY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rotate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rotate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartCentr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartCentr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartLeftDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartLeftDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
